version: 2

variables:
  context: &context org-context
  working_directory: &working_directory /go/src/github.com/Code-Hex/shibafu
common_steps:
  restore_cache_modules: &restore_cache_modules
    keys:
      - go-mod-v1-{{ checksum "go.sum" }}
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: *working_directory
    steps:
      - checkout
      - restore_cache: *restore_cache_modules
      - run:
          name: Test
          command: go test -v -race ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
    version: 2
    test-workflow:
      jobs:
        - build:
            context: *context
            filters:
              tags:
                only: /.*/
